ejecutarPython:
	python3 main.py

ejecutarGo:
	go run golang/main.go

ejecutarClienteRuby:
	ruby ruby/cliente.rb

ejecutarServidorRuby:
	ruby ruby/servidor.rb

instalar:
	@echo "Instalando dependencias..."
	pip install -r requirements.txt

all:
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."
